### ISSUE TITLE
Brainstorming about miq_bot_2

### ISSUE THREAD

**Issue by skateman** [ManageIQ/miq_bot#102]
- [ ] make the bot OpenShift compatible (provides a public URL)
- [ ] use webhooks instead of recurring jobs where possible (public URL is needed)
- [ ] convert workers to ActiveJob for better Rails support 
- [ ] create a generic `Linter` class to support pluggable linters
- [ ] use the GitHub statuses API instead of comments where possible #91 
- [ ] add a "Sign in with GitHub" feature for authorization/authentication
- [ ] create a UI, where all the linting issues are shown with embedded code snippets
- [ ] UI also for Gemfile changes, where @jprause & @jvlcek can have an ACK button (?)

**Comment by chriskacerguis** [comment]
@skateman has any work been done on this @Fryguy mentioned that you might have done some of this.   I'm going to start working on a V2 and I didn't want to dup efforts.

**Comment by chriskacerguis** [comment]
@miq-bot set_milestone Bot v2

**Comment by skateman** [comment]
@chriskacerguis yes, ping me on gitter or IRC

**Comment by chriskacerguis** [comment]
@skateman Let's keep the conversation here.  Maybe could you update this issue with what is done and not done (or maybe break it into a few tickets)?

**Comment by skateman** [comment]
So i talked to the OpenShift guys a few months ago and we can run the bot on up to 16 gears. I have an example rails controller for handling PR webhooks. I also created a generic linter by using [this gem](https://github.com/mmozuras/pronto). Unfortunately I had no time to integrate these things to the miq-bot :disappointed:
