### ISSUE TITLE
miq_bot does not honor rubocop's exclude list

### ISSUE THREAD

**Issue by mzazrivec** [ManageIQ/miq_bot#149]
We are calling rubocop with files as arguments and this causes rubocop to ignore the list of excluded files.

It would be nice to somehow pass the ignored file list to the running pipeline.

Case in point: https://github.com/ManageIQ/manageiq/pull/5700

`config/toolbar_strings.rb` has been added to exclude list in rubocop's configuration,
yet the file is being checked by rubocop for errors.

**Comment by jrafanie** [comment]
Adding screenshot so all the information is here:

![screen shot 2015-12-11 at 10 19 56 am](https://cloud.githubusercontent.com/assets/19339/11747361/d304798c-9ff0-11e5-9351-2ba1c9f337e3.png)

**Comment by Fryguy** [comment]
This should be fixed since the switch to rugged where we now extract all the relevant to a temp dir and just rubocop the entire directory.
