### ISSUE TITLE
Dev setup revamp needed

### ISSUE THREAD

**Issue by chrisarcand** [ManageIQ/miq_bot#156]
We should probably do a little revamping of the setup doc, add some of the steps to a setup script/task, and most importantly clarify some development.yaml stuff. For example, I just noticed that you _must_ use a repo underneath an organization, not just any user (that's fine, we should note that though - I set up my own test user/repo/etc before I fired this up and Octokit screamed at me :confused: )

**Comment by chriskacerguis** [comment]
@miq-bot set_milestone Bot v2
