### ISSUE TITLE
Scripts to Rull them All

### ISSUE THREAD

**Issue by juliancheal** [ManageIQ/miq_bot#175]
We should implement https://github.com/github/scripts-to-rule-them-all

We already kinda have something like this in https://github.com/ManageIQ/manageiq/tree/master/bin

miq_bot assign @juliancheal

**Comment by juliancheal** [comment]
@miq-bot assign @juliancheal

**Comment by juliancheal** [comment]
Kinda duplicate/follow on from https://github.com/ManageIQ/miq_bot/issues/156

**Comment by chriskacerguis** [comment]
@miq-bot set_milestone Bot v2
