### ISSUE TITLE
Add closing of stale PRs

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/miq_bot#184]
Add the ability to close PRs that haven't been updated in >= 30 days.  Flow would be...
at the 30 day mark add the `stale` tag...
if have `stale` tag, and PR is updated, remove `stale` tag.
if after another 30 days, no update, close the PR

**Comment by chriskacerguis** [comment]
@miq-bot set_milestone Bot v2

**Comment by Fryguy** [comment]
duplicate of https://github.com/ManageIQ/miq_bot/issues/76 ?

**Comment by chriskacerguis** [comment]
dup closing.
