### ISSUE TITLE
Update GithubNotificationMonitor to use GitHub gem

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/miq_bot#187]
the GithubNotificationMonitor was the very first thing written for the bot, so it has some of the oldest legacy stuff.  We should change the GithubNotificationMonitor to use the github gem (or more specifically, the MiqToolsServices::Github class, which is a service wrapper around the gem)

**Comment by chriskacerguis** [comment]
@miq-bot set_milestone Bot v2

**Comment by chrisarcand** [comment]
Replaced by #290
