### ISSUE TITLE
Rubocop check is done against hidden merge commit but links to the tip of PR branch

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/miq_bot#231]
For this PR:  https://github.com/ManageIQ/manageiq/pull/10459

The bot was complaining with this:

> Checked commits cben@ef76780~...b608cbb with ruby 2.2.5, rubocop 0.37.2, and haml-lint 0.16.1
> 3 files checked, 2 offenses detected
>
> app/controllers/report_controller/reports/editor.rb
>
 >❗️ - Line 1558, Col 37 - Style/ExtraSpacing - Unnecessary spacing detected.
 >❗️ - Line 1559, Col 33 - Style/ExtraSpacing - Unnecessary spacing detected.

Copying some details discussed in gitter.

* After checking out this PR and trying rubocop 0.37.2, we can't recreate the whitespace complaints.
* After rebasing that PR locally, we get these complaints on line 1558 and 1559 BUT, the lines rubocop complains about are not the lines changed in this PR:

```
app/controllers/report_controller/reports/editor.rb:1558:37: C: Unnecessary spacing detected.
    includes.each_pair do |key, inc|              # Check each included table
                                    ^^^^^^^^^^^^^
app/controllers/report_controller/reports/editor.rb:1559:33: C: Unnecessary spacing detected.
      next unless inc["include"]                           # Does the included table have an include?
```

So:

* the bot is reporting it's checking the tip of the PR branch: `cben@ef76780~...b608cbb`
* it links to the files at the PR tip commit: b608cbb33708f36afba4ae5b3a108b1d9aaea9bc
* But it's actually testing the hidden merge commit that travis uses: https://github.com/ManageIQ/manageiq/commit/add61d84b759260045b9d4a97c484e02ddc08b8b and using the line numbers from that for any complaints
* BUT, it's also using the MERGE commit line numbers at the tip of the PR branch for the links to the offending line instead of either both (merge commit line numbers and merge commit link) or (PR tip line numbers and PR tip commit link)

So, we should be either
* testing the PR at commit b608cbb (the tip of the PR branch)
* or change the report information to say `Checked add61d84 (Merge b608cbb into 814d77c)` with links to the files at add61d84

**Comment by cben** [comment]
Neat that Github allows linking to the hidden merge commit!
(well, it makes sense.  they wanted `git fetch remote pull/NNN/merge` to work so actually creating the commit is easier than faking it.  still neat.)

**Comment by jrafanie** [comment]
> Neat that Github allows linking to the hidden merge commit!
> (well, it makes sense. they wanted git fetch remote pull/NNN/merge to work so actually creating the commit is easier than faking it. still neat.)

Neat, yes, but it causes some strange issues like this sometimes.

**Comment by bdunne** [comment]
@jrafanie It's not using the hidden merge commit.  We were going to use that, but it's not always available.  So the bot creates its own merge commit.  This also prevents consuming resources (running rubocop) on unmergable PRs.

https://github.com/ManageIQ/miq_bot/blob/master/lib/git_service/branch.rb#L17
https://github.com/ManageIQ/miq_bot/blob/master/lib/git_service/branch.rb#L40

**Comment by jrafanie** [comment]
@bdunne interesting.  So, it's a the github hidden merge commit but it could be a hidden one we create.  I don't know if this is only a problem if the PR is not rebased for a while or happens often with PRs less than 1 week old.

**Comment by Fryguy** [comment]
@bdunne I think we should make the merge commit to veryify mergeability, but then use the tip of the branch instead.
