### ISSUE TITLE
Track Pivotal Tracker Stories / update their status as things are merged

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/miq_bot#241]
Would like to add a new command, "add_pt" the format would be:
```miq-bot add_pt [pivitol_tracker_story_id]```
Then using the PT API it would attach the PR to the story id, and track it's status.  So, the PR being opened would set the story to "Finished" and once it is merged, it would get changed to "Delivered"

**Comment by Fryguy** [comment]
Cool idea...Alternately (perhaps in addition?), would it make sense to embed the tracker id in a commit message like we do with GitHub issues and BZ URLs?  This way you also get the tracking locally that you get with Git commits.  That is, when you are tracking down issues by blaming code, you would see the tracker id in the git commit, and then can walk to the pivotal issue from there.  This is the workflow that many use when they hit BZs in commit message as well as the very old Fogbugz tickets that now live in redhat Bugzilla.

**Comment by chriskacerguis** [comment]
Either way works.  Since we are putting this in the miq bot, now that I think about it, it will need the full link so it can get the project AND story id

**Comment by Fryguy** [comment]
I double checked and the story id is sufficient. For example: https://www.pivotaltracker.com/story/show/132786099 works and will take you to the story directly (it redirects to the correct full project URL of https://www.pivotaltracker.com/n/projects/1608513/stories/132786099).  I'm guessing that their API can do direct-to-story as well.

So I'm thinking for the commit message something like
- PT#132786099
- PT 132786099
- Pivotal: 132786099

What do you think, or do you have other preferences on the format?

**Comment by chriskacerguis** [comment]
That works.

**Comment by Fryguy** [comment]
If this is tracked via commits, it could be done directly...if this is done via PR comments, then this would probably depend on #363
