### ISSUE TITLE
Required info -> Pivotal Tracker Story / Link

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/miq_bot#251]
Would like to get reminded to add a Pivotal Tracker Story / Link to an issue.  Also, maybe add a "need info" label.

**Comment by jjlangholtz** [comment]
Some initial thoughts on implementation:

* Do we need to add the `need info` label to each repo or will the GH api create the label if it doesn't exist? I remember testing this out before but I don't remember off the top of my head.
* Build on `PivotalPrChecker`, when worker runs check for pivotal ids as usual, if ids are empty add the label and comment on the PR. In `#update_pivotal_story` remove label if it exists
* Adding/removing `need info` label is very similar to the `PrMergeabilityChecker` and `unmergeable` tag, maybe this behavior can be pulled out into a mixin and shared?

@Fryguy does this approach make sense?
