### ISSUE TITLE
Add GitHub rate limit screen

### ISSUE THREAD

**Issue by chrisarcand** [ManageIQ/miq_bot#266]
We should add a screen to the UI tracking the GitHub rate limit. We should plot the rate limit over time so we have a better idea of how to optimize our caching, etc, and I don't really know how to measure improvement at this point beyond staring at debug logs.

I propose a simple poll at 24 hour increments, storing it, graphing it. Documentation on this endpoint (which doesn't count towards the rate limit, btw) is here: https://developer.github.com/v3/rate_limit/

**Comment by bdunne** [comment]
@chrisarcand Is there more that you want to do for this?  I think it could be considered done, right?

**Comment by chrisarcand** [comment]
Yabetcha.
