### ISSUE TITLE
On a merged PR, set the milestone to the current Sprint milestone.

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/miq_bot#27]
If not already set, set the milestone.  Give a grace period of a few minutes or so, possibly, to not step on a merger's actions.

**Comment by bdunne** [comment]
@Fryguy Please review.  I think I mentioned this to you the other day and you disagreed with it because of potential changes to our use of milestones.

**Comment by Fryguy** [comment]
Depends on #363

**Comment by JPrause** [comment]
+100 this would be very helpful in regards to sprint statistics.
Every sprint, we end up with at least 10 PRs without the milestone set.
(as an aside, there are instances where the milestone is set, but it shouldn't be set. I'll try to find an example when it happens)

**Comment by bdunne** [comment]
Closing as we no longer set sprint milestones
