### ISSUE TITLE
Complain in PR's when illegal values are found in the diff content

### ISSUE THREAD

**Issue by bdunne** [ManageIQ/miq_bot#32]
The bot should complain in a PR if the diff contents contain certain unwanted strings like "cfme".

**Comment by Fryguy** [comment]
:heart:

**Comment by brandondunne** [comment]
Maybe file names too?

**Comment by Fryguy** [comment]
some others I thought of:

- WIP in a commit message (particularly the commit subject)
- git pause text in a commit message.

**Comment by Fryguy** [comment]
Also
- a revert of a commit in the same branch.

**Comment by Fryguy** [comment]
Also, `byebug`, `binding.pry`
Maybe `byebug_term`?
