### ISSUE TITLE
Cannot remove sql migration label

### ISSUE THREAD

**Issue by moolitayer** [ManageIQ/miq_bot#338]
This probably has to be generalized, but after extracting files touching sql migrations from a PR in ManageIQ there is no way for me to remove the `sql migration` label.

Not super important, but would be helpful

**Comment by Fryguy** [comment]
@moolitayer You should be able to do `@miq-bot remove_label sql migration`  See also https://github.com/ManageIQ/miq_bot#requested-tasks
