### ISSUE TITLE
miq_bot marked a merged PR wip after a comment

### ISSUE THREAD

**Issue by cben** [ManageIQ/miq_bot#342]
See https://github.com/ManageIQ/manageiq/pull/10944#issuecomment-298335139
Happened immediately after my comment.

1. I don't see what specifically made it decide it's WIP?
2. in any case the PR is already merged, makes no sense to mark WIP.

**Comment by cben** [comment]
and now it removed wip label by itself, but the `[WIP]` in title remains

**Comment by Fryguy** [comment]
We are seeing some weird intermittent issue where the bot randomly decides to go back and replay old messages.  I've yet to narrow down why this occurs.
