### ISSUE TITLE
Rule to Move BZ to POST

### ISSUE THREAD

**Issue by mfeifer** [ManageIQ/miq_bot#350]
We need a way to automatically move a BZ to POST, when a PR has been merged.  Suggested wording:  "Fixes BZxxxxx"

**Comment by mfeifer** [comment]
Need this to help engineers get things moved to testing by changing the BZ status.

**Comment by mfeifer** [comment]
What about edge case with 2 PRs for one BZ?

**Comment by Fryguy** [comment]
> What about edge case with 2 PRs for one BZ?

I think we can assume that if someone tags one as Fixes, then it's fixed.  It's up to the developer to not mark two PRs as "Fixes"

**Comment by Fryguy** [comment]
Depends on #363
