### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by europ** [ManageIQ/miq_bot#369]
By following the steps in setup of [miq_bot](https://github.com/ManageIQ/miq_bot), the 6th step fails.

Using rbenv 2.4.1.

Unexpected segmentation fault after executing command:
```
bundle exec rails runner 'Repo.create_from_github!("europ/miq_bot_testrepo", "https://github.com/europ/miq_bot_testrepo.git")'
```

Console:
[SegmentationFault.txt](https://github.com/ManageIQ/miq_bot/files/1466369/SegmentationFault.txt)

Test repository:
https://github.com/europ/miq_bot_testrepo

/cc @Fryguy

**Comment by Fryguy** [comment]
wow I've never seen this before.  As rugged is a compiled gem, it's possible mayba that you upgraded Ruby, but didn't recompile it against the new ruby?  Only thing I can think of is just whack your rugged gem and recompile.

```
gem uninstall rugged
bundle update
```

**Comment by chrisarcand** [comment]
⚠️ @europ Random aside as you're following the setup steps: you cannot use miq-bot on a non-organization based repository (you're trying to use one on your user, which, sadly, won't work. It's an known issue that's dumb but is what it is).
