### ISSUE TITLE
Issue Manager: Can't see private members

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/miq_bot#37]
The Github API only shows members who publicize their membership, so when the issue manager filters commands by user, it doesn't know about private users.  See https://developer.github.com/v3/orgs/members/#members-list

**Comment by jrafanie** [comment]
What can we do about that?  Should we reply with a useful message that they need to publicize their membership?

**Comment by Fryguy** [comment]
I'm not sure we can do anything...I don't think a message is good, because it would appear for any person.  It's like a chicken/egg problem...if we knew they were in the org, we wouldn't need the message :)

**Comment by Fryguy** [comment]
The other option is to make the bot an "owner" account, but I *really* don't want to do that.

**Comment by Fryguy** [comment]
I don't think we can fix this so I've just documented it in the README.
