### ISSUE TITLE
Repos not configured with .yamllint files get bot error comments

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/miq_bot#392]
There are a few approaches to fixing this...not sure what's best

- When the yamllint files don't exist, use a shared file from guides
- When the yamllint files don't exist, assuming linting is disabled and don't lint at all
- Add enable/disable support for individual linters, then fail or fallback when the files don't exist
- Send an email instead of making a comment

Also, should the same rules apply for haml lint and rubocop as well?

@bdunne @imtayadeway Thoughts?

**Comment by bdunne** [comment]
Closing as a duplicate of #379 and added https://github.com/ManageIQ/miq_bot/issues/379#issuecomment-644187866
