### ISSUE TITLE
Bot should honor commands to reload_labels and reload_milestones to "learn new labels/milestones"

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/miq_bot#40]
It should honor: `@miq-bot reload_labels` and `@miq-bot reload_milestones`, or `@miq-bot reload_repo` if you're in the organization.

We [cache these values at startup](https://github.com/ManageIQ/miq_bot/blob/d375a5fd915ea71a4e3bc4d9bed7071841b925e7/lib/bot/githubapi/repo.rb#L10-11) and we have to restart the bot to get new labels or milestones.

[Existing code checks](https://github.com/ManageIQ/miq_bot/blob/d375a5fd915ea71a4e3bc4d9bed7071841b925e7/lib/bot/issue_manager.rb#L132) for these labels before allowing the user to assign that label

**Comment by jrafanie** [comment]
@miq-bot add_label enhancement

**Comment by jrafanie** [comment]
:cry: bot doesn't do meta-issues.

**Comment by Fryguy** [comment]
Found a nice way to do this without exposing it to the end user...should have a PR soon.

**Comment by Fryguy** [comment]
Made the PR.  The alternate approach there is to just reload the cache and recheck if we get an unknown label/milstone/user.
