### ISSUE TITLE
Restarting errored Travis builds

### ISSUE THREAD

**Issue by bdunne** [ManageIQ/miq_bot#41]
Problem:  Sometimes Travis build error (for timeouts or other reasons than code failures).  I don't have permissions to restart because I'm not a merger on manageiq.  So I need to either close and re-open the PR to re-run everything or ping someone to re-run the component that errored.

Possible solutions: 
- Allow a PR comment like "@miq-bot travis_restart vmdb"
- Let the bot automatically restart errored builds (not sure if there are potential loop conditions)

**Comment by Fryguy** [comment]
I wonder if we could do both.  The first would be for some kind of failure, maybe sporadic test failure or something.  The second could auto-pickup known issues like when travis timeouts and you get the "No change for 10 minutes" thing in the log.

**Comment by blomquisg** [comment]
So, I think this should do 3 things:

1) update an existing issue with the details of the failure
  * if build links are persistent links, we could just link to the build and to the PR
2) restart the failed build(s)
3) comment in the PR that the build was restarted

**Comment by imtayadeway** [comment]
was this resolved in https://github.com/ManageIQ/miq_bot/pull/59 ?

**Comment by chrisarcand** [comment]
I think it was, for random failures. 

> Allow a PR comment like "@miq-bot travis_restart vmdb"

Could do this, but also keep in mind that contributors can simply update their latest SHA and push to restart builds without write access. (`git commit --amend; git push --force`)

**Comment by bdunne** [comment]
With the current state of ManageIQ/manageiq, I think this is no longer an issue.  It was more of a problem with many test suites taking a long time.  In the current state, I think the rebase / force push is acceptable.

Please reopen if anyone disagrees.
