### ISSUE TITLE
Warn against user pings (@ + "username") in commit messages

### ISSUE THREAD

**Issue by NickLaMuro** [ManageIQ/miq_bot#414]
GitHub notifications will spam a user everytime a commit shows up with a user's `@username` in the subject.

Having a simple check for each commit on push (like the `puts` check) can prevent this from happening, or at least give the review a heads-up when it happens.

**Comment by chrisarcand** [comment]
WAT completely unacceptable, how are you supposed to troll @jrafanie then

**Comment by Fryguy** [comment]
People may want to put the `@foo` in code blocks though, which should be acceptable.  Whatever detection we use should allow that.

**Comment by jrafanie** [comment]
I approve of this feature request

**Comment by NickLaMuro** [comment]
> People may want to put the @foo in code blocks though, which should be acceptable. Whatever detection we use should allow that.

My thought on this is that it would be a warning, not a hard "prevent user from merging" type enforcement.  Just something that doesn't require reviewers to go through each commit message and read them...

_Nick has a realization and cries in a corner because no one reads his commit messages..._

**Comment by NickLaMuro** [comment]
LaMuro, Nicholas:  _The book that nobody is willing to read_.  Minneapolis:  Self Published, 2018
