### ISSUE TITLE
Warn if a PR changes application code without tests

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/miq_bot#42]
It would be nice if the bot pinged the author of this PR to ensure they clarify why tests aren't included in the PR.  Many times the reviewer needs to ask this and either forgets or feels like the bad guy.  The bot should do this automatically to keep humans out of it.

It could be as simple as checking for any changes in test or spec directories.

“Please clarify why this PR doesn't include tests, whether existing tests cover the code in the PR or some other reason.”

**Comment by bdunne** [comment]
Too hard to enforce
