### ISSUE TITLE
`miq_bot` update issues/checklist

### ISSUE THREAD

**Issue by NickLaMuro** [ManageIQ/miq_bot#427]
I am opening this issue to make note of and create a checklist for a number of issues with `miq_bot` when working on newer versions of Ruby/Rails:

- [x] `rails` is out of date (causes deprecation warnings with the `pg` gem)  ~~https://github.com/ManageIQ/miq_bot/pull/430~~ ~~https://github.com/ManageIQ/miq_bot/pull/435~~ https://github.com/ManageIQ/miq_bot/pull/466
- [x] `active_bugzilla` doesn't work on Ruby 2.4+ (`xmlrpc` was removed from stdlib)  https://github.com/ManageIQ/miq_bot/pull/466
  - Note:  This should really be addressed from `active_bugzilla` which there is a lot that needs to be updated there as well
  - Update:  Also, turns out Bugzilla dropped support for xmlrpc, so we now need to support the JSON API in that gem as well.
  - Update 2: As [mentioned below](https://github.com/ManageIQ/miq_bot/issues/427#issuecomment-463027982), this was addressed by simply removing the need for `xmlrpc`.

Going to try and address these myself, and might add to this list, but if you see PRs poping up from me, that is probably why.

**Comment by juliancheal** [comment]
@NickLaMuro hey Nick, these are both fixed with #430

**Comment by NickLaMuro** [comment]
@juliancheal This just fixes the first one.  The second one is unrelated to your fix.

**Comment by NickLaMuro** [comment]
> The second one is unrelated to your fix.

Looks like I need to clarify:

The update to `xmlrpc` will allow the `miq_bot` project to bundle, but it will completely brick the `active_bugzilla` gem since it they removed the parser that we switched to in https://github.com/ManageIQ/active_bugzilla/pull/49 as  it was removed when it was still in ruby core:

- `XMLTreeParser` remove from `xmlrpc` (which worked with `xmlparser`): ruby/ruby@d8e3a92
- `xmlrpc` moved to a gem: https://bugs.ruby-lang.org/issues/12160

(ripped from a further discussion I had in the [bot channel](https://gitter.im/ManageIQ/miq_bot?at=5bf593f3d24f9324d22ff46d))

We don't have tests around that, since we stub it out, but I was attempting to address that here:

https://github.com/ManageIQ/active_bugzilla/pull/52

And probably switching to something like `ox` for the XML parsing since it is actively maintained, contains a xmlrpc parser, and works on 1.9.3 - 2.5+, where `xmlparser` has not been updated in years and now doesn't have a xmlrpc parser either.

**Comment by juliancheal** [comment]
Thanks for the update @NickLaMuro.

**Comment by NickLaMuro** [comment]
Gave an update in Julian's PR (more details there if interested):

https://github.com/ManageIQ/miq_bot/pull/430#discussion_r238482558

So both issues will be fixed via #430 being merged.  Will update the PR description for the second task item to include #430 as well.

**Comment by NickLaMuro** [comment]
Note:  Updated the PR for fixing `active_bugzilla` with https://github.com/ManageIQ/miq_bot/pull/434

Reason being is it was decided that `active_bugzilla` doesn't provide much for us here, and having a simple service class doing the heavy lifting itself was sufficient (instead of pulling in a library).  So #434 just removes `active_bugzilla` from the project, fixing a few other issues along the way.

Discussion about it starting here (with a bit of context):  https://gitter.im/ManageIQ/manageiq?at=5c6327cc5095f6660ce2230b

**Comment by gtanzillo** [comment]
@NickLaMuro Is this still a valid issue?

**Comment by NickLaMuro** [comment]
@gtanzillo nope, closed via https://github.com/ManageIQ/miq_bot/pull/466

Updated the description and I will now close this issue.  Thanks!
