### ISSUE TITLE
Warn if a PR does not have a component (purple) label

### ISSUE THREAD

**Issue by blomquisg** [ManageIQ/miq_bot#43]
As a reviewer, I would like to be able to find all PRs that are in the Providers space easily.  The only way I know how to do this is to query for all PRs that have a providers label.  This relies on someone setting the providers label on provider-specific PRs.

I would like it better if the bot simply nagged the PR author to label the PR.

Scan for all PRs older than 1 day and that do not have a component (blue) label.  For each PR in this category, send an email to the commiters list and to the PR author.

The Email should contain the link to the PR as well as some short instructions on how to apply a label if the PR author does not have access to label PRs.

Component (or, blue) labels include:
- api
- appliance
- fleecing
- providers

... and may contain slashes:
- providers/containers
- appliance/console

**Comment by jrafanie** [comment]
I would be fine if the bot just commented on the issue/PR  :+1:

**Comment by Fryguy** [comment]
I like it. :+1:

I wonder if there's a way programmatically to just get the list of labels by color

Also, sometimes there is no component, like when someone fixes a problem with rspec or something.  Maybe we need an "other" component

I was also thinking something similar to this for
- setting milestones after merge
- setting a bug/enhancement/test/ruby2/rails4 label

**Comment by blomquisg** [comment]
> I would be fine if the bot just commented on the issue/PR

@jrafanie, oh yeah, sounds good to me.

> I was also thinking...

@Fryguy, yeah, definitely.  Especially the "setting milestones after merge", because I *always* forget to do that.

**Comment by bdunne** [comment]
Please see #26 for post-merge reminders
