### ISSUE TITLE
Issue was closed after 6 months, but was not marked as stale beforehand

### ISSUE THREAD

**Issue by JPrause** [ManageIQ/miq_bot#437]
Hmmm, more bot weirdness:
https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/234#event-2192793160

Shouldn't it have first been marked stale? Seems it closed the issue after 6 months with no updates.

**Comment by NickLaMuro** [comment]
FYI:  This is currently will currently be handled as part of the work being done for https://github.com/ManageIQ/miq_bot/issues/390
