### ISSUE TITLE
Issue was closed after 6 months but I cannot reopen

### ISSUE THREAD

**Issue by lpichler** [ManageIQ/miq_bot#439]
<img width="731" alt="Screenshot 2019-04-01 at 11 07 56" src="https://user-images.githubusercontent.com/14937244/55316313-69d1be80-546e-11e9-9b30-42cd65990f43.png">

**Comment by Fryguy** [comment]
The screenshot cuts it off, but were you the original author of the issue?  Which issue is it?

**Comment by lpichler** [comment]
@Fryguy I guess I was author but there is other example https://github.com/ManageIQ/manageiq/pull/17977 

**Example of PR closed by miq bot:** (the button is missing here, so I cannot reopen it)

https://github.com/ManageIQ/manageiq/pull/17977

<img width="885" alt="Screenshot 2019-04-23 at 18 13 57" src="https://user-images.githubusercontent.com/14937244/56597853-9dc67c80-65f3-11e9-8031-9d446f8fb129.png">

**Example of PR closed by me:** (there is the button )
<img width="878" alt="Screenshot 2019-04-23 at 18 10 55" src="https://user-images.githubusercontent.com/14937244/56597678-40cac680-65f3-11e9-9f19-6a138a4933d1.png">
