### ISSUE TITLE
Extracted files are not written with the correct file permissions

### ISSUE THREAD

**Issue by bdunne** [ManageIQ/miq_bot#445]
https://github.com/ManageIQ/miq_bot/blob/1791444d3b164879d24f61941403aed64ca4e590/lib/linter/base.rb#L61

**Comment by NickLaMuro** [comment]
Thanks @bdunne , I thought this was acting weird.

I think I did have to do a `git update-index --chmod=+x tools/miqversions.rb` in the referenced PR which the bot did catch me on (maybe...), but besides that it seems like this is the culprit of the bot's issues persisting even after that.  Thanks again for looking into this!

**Comment by Fryguy** [comment]
Closed in #465
