### ISSUE TITLE
Github API Deprecation notice

### ISSUE THREAD

**Issue by NickLaMuro** [ManageIQ/miq_bot#467]
Got this email yesterday while testing #454

```
[GitHub] Deprecation Notice
---------------------------

Hi @grumpynick-bot,

You recently used a password to access an endpoint through the GitHub API using Octokit Ruby Gem 4.8.0. We will deprecate basic authentication using password to this endpoint soon:

https://api.github.com/repositories/[REDACTED]/notifications?all=false&per_page=100

We recommend using a personal access token (PAT) with the appropriate scope to access this endpoint instead. Visit https://github.com/settings/tokens for more information.

Thanks,
The GitHub Team
```

**Comment by jrafanie** [comment]
`@grumpynick-bot,` ❤️ 😆 🤣  ❤️

**Comment by Fryguy** [comment]
Thanks for the update... Luckily we already use a personal access token in deployment.

**Comment by NickLaMuro** [comment]
@Fryguy before you just close it like that, can you then explain this...

https://github.com/ManageIQ/miq_bot/blob/9ad019ed7aac976baa4715b4825351b6e9ece5ec/lib/github_service.rb#L121-L122

If we were using an `access_token`, then shouldn't the config instead say `.access_token`, and not `.password`?

**Comment by Fryguy** [comment]
GitHub's Password field can take either a password or an access token, hance why I closed it because it already works.  But yeah, since "password" is literally going way, I think changing the option name is a good change.
