### ISSUE TITLE
Document how to test the bot with a sandbox repo

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/miq_bot#47]

**Comment by imtayadeway** [comment]
was this resolved in https://github.com/ManageIQ/miq_bot/commit/6df1397b91df7e21e10fd3bf34338a5761661ea4, or does it need more documentation?

**Comment by jrafanie** [comment]
:+1:  resolved in https://github.com/ManageIQ/miq_bot/commit/6df1397b91df7e21e10fd3bf34338a5761661ea4
