### ISSUE TITLE
[RFE] Botify request to backport

### ISSUE THREAD

**Issue by chessbyte** [ManageIQ/miq_bot#475]
Process described [here](https://github.com/ManageIQ/guides/blob/master/backport_process.md).

We need an enhancement to miq-bot to convert requests to `add label release_to_backport_to/yes` to be interpreted as `add label release_to_backport_to/yes?` for anyone who is not part of the [triage team](https://github.com/orgs/ManageIQ/teams/core-triage).  If it is too hard to limit to that group, then do it for everyone and the people with the privileges to change labels without the bot will get things done that way.

Also, not sure if we should disallow removal of labels `release_to_backport_to/yes` and `release_to_backport_to/no`

**Comment by Fryguy** [comment]
Do we want a `yes` request to be straight converted to `yes?`, or is it sufficient to disallow `yes` and allow `yes?`

**Comment by chessbyte** [comment]
I think `yes` should be converted to `yes?` automagically
