### ISSUE TITLE
[Bug] Migration bug after Rails 5.2

### ISSUE THREAD

**Issue by NickLaMuro** [ManageIQ/miq_bot#489]
So while working on https://github.com/ManageIQ/miq_bot/pull/469 and was asked to change a column in the database, I ended up re-running migrations entirely by doing the following:

```console
$ RAILS_ENV=development bundle exec rake db:environment:set db:drop db:create db:migrate

...

== 20150730043503 CreateBatchTables: migrating ================================
-- create_table(:batch_jobs, {})
   -> 0.0027s
   -- create_table(:batch_entries, {})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Index name 'index_batch_entries_on_batch_job_id' on table 'batch_entries' already exists
activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:1160:in `add_index_options'
activerecord-5.2.4.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:465:in `add_index'
activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:315:in `block in create_table'
activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:314:in `each'
activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:314:in `create_table'
activerecord-5.2.4.1/lib/active_record/migration.rb:871:in `block in method_missing'
activerecord-5.2.4.1/lib/active_record/migration.rb:840:in `block in say_with_time'
activerecord-5.2.4.1/lib/active_record/migration.rb:840:in `say_with_time'
activerecord-5.2.4.1/lib/active_record/migration.rb:860:in `method_missing'
activerecord-5.2.4.1/lib/active_record/migration/compatibility.rb:34:in `create_table'
miq_bot/db/migrate/20150730043503_create_batch_tables.rb:8:in `change'
```

The error returned was remedied by doing one of the following:

1.  Commenting/deleting out this line:
  
  https://github.com/ManageIQ/miq_bot/blob/ccbac595301d617cf270c3718e30002df7cdefc9/db/migrate/20150730043503_create_batch_tables.rb#L10
  
2. Changing the migration to inherit from `ActiveRecord::Migration[4.2]` instead of `5.1`.

Option 2 is probably the more "correct" approach, but does end up changing the `db/schema.rb`, and was technically written for Rails 4.0, and you can't use that version with the versioned migration classes.

```
ArgumentError:  Unknown migration version "4.0"; expected one of "4.2", "5.0", "5.1", "5.2"
```

* * *

So "asking the audience" on what we think is the best approach to fix this, and I can put together a PR.  If "Option 2", we probably should fix all of the migrations so they are based off the closest Rails version available, so that will be a much larger change.

**Comment by Fryguy** [comment]
I'm thinking Option 2.

**Comment by NickLaMuro** [comment]
Okay, I might try looking into this today then.  Option 1 was the one line change shown above, so the other one will take a bit more work to do, but should be manageable.

**Comment by NickLaMuro** [comment]
@miq-bot assign @NickLaMuro

**Comment by NickLaMuro** [comment]
FINE!  BE THAT WAY!!!1!

😤

**Comment by NickLaMuro** [comment]
Alright, opened up a fix in https://github.com/ManageIQ/miq_bot/pull/491
