### ISSUE TITLE
HAML lint ignores config

### ISSUE THREAD

**Issue by himdel** [ManageIQ/miq_bot#490]
Noticed in https://github.com/ManageIQ/manageiq-ui-classic/pull/6759#issuecomment-600113533..

```
Checked commits hstastna/manageiq-ui-classic@ab61ba5~...9cf867d with ruby 2.5.7, rubocop 0.69.0, haml-lint 0.28.0, and yamllint
5 files checked, 8 offenses detected

app/views/layouts/angular/_paging_div_buttons.html.haml

 warning - Line 1 - Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
 warning - Line 1 - Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
 warning - Line 1 - Layout/TrailingBlankLines: Final newline missing.
 warning - Line 1 - Style/FrozenStringLiteralComment: Missing magic comment # frozen_string_literal: true.
 warning - Line 1 - Style/HashSyntax: Use the new Ruby 1.9 hash syntax.
 warning - Line 1 - Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
 warning - Line 1 - id attribute must be in lisp-case

app/views/vm/show.html.haml

 warning - Line 14 - Style/HashSyntax: Use the new Ruby 1.9 hash syntax.
```

The first file being just `#angular_paging_div_buttons{:align => "right"}`.

When I run `haml-lint` locally in the ui (both 0.28.0, and 0.35.0), it outputs just the 

```
 warning - Line 1 - Layout/TrailingBlankLines: Final newline missing.
 warning - Line 1 - id attribute must be in lisp-case
```

But, the bot adds the other warning, despite `SpaceInsideHashLiteralBraces` being set to the exact opposite in [.haml-lint.yml](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/.haml-lint.yml#L79).

Looks like the bot was updated from haml-lint 0.20.0 to 0.28.0 in the last 14 days, could be related.
(But again, running 0.28.0 locally works as expected.)

**Comment by Fryguy** [comment]
The link you offered shows `SpaceInsideHashAttributes`, but the complaint is on `SpaceInsideHashLiteralBraces` ?
