### ISSUE TITLE
Upgrade rubocop/haml-lint

### ISSUE THREAD

**Issue by NickLaMuro** [ManageIQ/miq_bot#496]
Based on some conversation here:

https://gitter.im/ManageIQ/miq_bot?at=5eb113dfb6dd230697a77f89

We are pretty out of date with `rubocop`, so this is probably worth while to do regardless of the `haml-lint` issues.

This probably isn't the only location that some changes need to be made (config changes probably need to happen in the ManageIQ/guides repo), but creating a tracking issue so we can keep track of the effort.

**Comment by NickLaMuro** [comment]
not sure if the bot looks at this repo... but...

@miq-bot assign @NickLaMuro 
@miq-bot add_label dependencies

**Comment by Fryguy** [comment]
Closing this as we rely on the rubocop updates from manageiq-style repo.  That repo can still get out of date, but this way it's centralized to one place.
