### ISSUE TITLE
haml linter is not working with the version of ruby being used by the miq_bot

### ISSUE THREAD

**Issue by jvlcek** [ManageIQ/miq_bot#515]
I changed a haml file and miq_bot reported:

 💣 💥 🔥 🚒 - Linter/Haml - Linter::Haml STDERR:
warning: parser/current is loading parser/ruby25, which recognizes
warning: 2.5.8-compliant syntax, but you are running 2.5.7.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.

Please see: 
https://github.com/ManageIQ/manageiq-ui-classic/pull/7230#issuecomment-664560125

**Comment by Fryguy** [comment]
@bdunne
