### ISSUE TITLE
Rubocop linter links no longer valid

### ISSUE THREAD

**Issue by himdel** [ManageIQ/miq_bot#535]
Looks like the docs links rubocop returns no longer work...

```
 exclamation - Line 31, Col 11 - Layout/MultilineMethodCallIndentation - Align .map with files_list on line 30.
```
links to https://rubydoc.info/gems/rubocop/0.82.0/RuboCop/Cop/Layout/MultilineMethodCallIndentation
Which claims there's no such gem as rubocop :(

It seems the correct link is something like https://docs.rubocop.org/rubocop/1.0/cops_layout.html#layoutmultilinemethodcallindentation
.. except they don't have versions < 1.0 :(.

**Comment by Fryguy** [comment]
Seems all of rubocop gems are missing on rubydoc.info.  Not sure if that's a transient thing, or if something else is going on.

**Comment by Fryguy** [comment]
Even so, I have a feeling the link generator will have to be rewritten now that a lot of the cops have been moved into child-gems, like rubocop-performance and rubocop-rails.

**Comment by Fryguy** [comment]
There seems to be a problem with rubydoc.info because even nokogiri and other gems are missing - See https://rubydoc.tenderapp.com/discussions/problems/764-documentation-for-gems-missing

Even so, I'd like to keep this issue open because of https://github.com/ManageIQ/miq_bot/issues/535#issuecomment-762965555

**Comment by Fryguy** [comment]
> https://rubydoc.tenderapp.com/discussions/problems/764-documentation-for-gems-missing#comment_48980977
> 
> We've just resolved this issue again and identified a case where it might crop back up so we're investigating the root issue now. Thanks for reporting this.

**Comment by Fryguy** [comment]
Link generator was rewritten in https://github.com/ManageIQ/miq_bot/pull/561, so closing this one
