### ISSUE TITLE
mimemagic via tracker_api causes build to fail

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/miq_bot#554]
tracker_api gem for Pivotal Tracker depends on mimemagic directly.  As such, the build currently fails unless we add in the shared-mime-info or drop pivotal tracker support.

**Comment by chessbyte** [comment]
What do we use PivotalTracker for in the bot?

**Comment by NickLaMuro** [comment]
@chessbyte We used to use it but I think that was dropped nearly 5 years ago:

https://github.com/ManageIQ/manageiq/pull/16003

@Fryguy should we just drop support for this (maybe in a separate PR)?

**Comment by Fryguy** [comment]
Yes, I suggested dropping support in the OP.

I don't know the level of difficultly for that, so if there was a fast path that just got things to work, I'd be ok with that for now.

**Comment by Fryguy** [comment]
Dropping via #570

**Comment by Fryguy** [comment]
dropping pivotal won't fix this issue, but I think it was fixed anyway in #558
