### ISSUE TITLE
Warn that t.timestamp(s) migration statements are changing default from null:true  to null:false

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/miq_bot#69]
We should detect migrations mentioning these statements without a null value and warn that the default is changing from true to false in rails 5.

From https://github.com/ManageIQ/manageiq/pull/3145
#### Use existing timestamp behavior of allowing nulls (t.timestamp, t.timestamps)

```
Fixes warning:
`#timestamp` was called without specifying an option for `null`.
In Rails 5, this behavior will change to `null: false`.
You should manually specify `null: true` to prevent the behavior of your existing migrations from changing.
```

**Comment by bdunne** [comment]
Is this still an issue?
