### ISSUE TITLE
Record the version of haml-lint in the PR comment

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/miq_bot#71]
See https://github.com/ManageIQ/miq_bot/blob/master/app/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder.rb#L48

@skateman Can you do this one?

**Comment by skateman** [comment]
@Fryguy sure!

**Comment by skateman** [comment]
@miq_bot assign @skateman

**Comment by skateman** [comment]
@miq-bot assign @skateman
