### ISSUE TITLE
Upgrade to ruby 2.2

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/miq_bot#75]
Started working on this here:
https://github.com/ManageIQ/miq_bot/compare/master...jrafanie:ruby22_support

**Comment by Fryguy** [comment]
Let's experiment with puma or one of the other servers

**Comment by Fryguy** [comment]
@brandondunne If we move to Ruby 2.2 will that affect deployment.

**Comment by brandondunne** [comment]
@Fryguy Yes, If we want ruby2.2 we'll have to update to the ruby220 SCL or switch to RVM/Chruby

**Comment by brandondunne** [comment]
The appliance has been upgraded to ruby 2.2.2
