### ISSUE TITLE
Bot should ping OPEN issues older than x days

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/miq_bot#76]
Ask the issue creator "What's the status on this issue?"

cc @chessbyte 

It should close OPEN issues older than (x + 2) days old, "Please reopen if this is still an issue."

**Comment by chriskacerguis** [comment]
@miq-bot set_milestone Bot v2

**Comment by chriskacerguis** [comment]
Thinking the flow would be (per our talk)...
at the 30 day mark add the stale tag...
if have stale tag, and PR is updated, remove stale tag.
if after another 30 days, no update, close the PR

**Comment by Fryguy** [comment]
Closed via #331
