### ISSUE TITLE
Bot should ping pull requests over x days old

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/miq_bot#77]
Perhaps similar rules as issues in #76 (close after x + 2 days) or do additional checks like "check mergeability"... maybe change the x value and the close after y days values compared to issues.

Pull requests can be easily re-opened if it's still worth looking at.

cc @chessbyte

**Comment by jrafanie** [comment]
Maybe it should also check the travis status also

**Comment by chriskacerguis** [comment]
@miq-bot set_milestone Bot v2

**Comment by Fryguy** [comment]
Closed via #331
