### ISSUE TITLE
Gemfile checker should be a commit_range handler, not a commit handler

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/miq_bot#78]
If you have two commits each with a new gem added to the Gemfile, gemfile checker will comment on the PR twice instead of once.

See below
![screen shot 2015-06-23 at 2 59 33 pm](https://cloud.githubusercontent.com/assets/19339/8314606/83b44dbc-19b8-11e5-82a6-13ca285dbf54.png)

This came from this PR:  https://github.com/miq-test/sandbox/pull/3/

**Comment by carbonin** [comment]
See below for new Gemfile tracker comment example.
![gemfilecheckerfixed](https://cloud.githubusercontent.com/assets/12697904/8339180/ba1032d8-1a83-11e5-948e-8a68ea0f7595.png)
