### ISSUE TITLE
Rubocop should not consider merged branches.

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/miq_bot#81]
This may actually be a problem with how we generate the commits list for a PR, but when someone does a merge from master (instead of a rebase), ALL of those commits are considered too.  We probably should just skip those commits for rubocop.

See the [rails 4 PR on ManageIQ](https://github.com/ManageIQ/manageiq/pull/2608) for a PR with a lot of "Merge branch 'master' into rails4 …" commits.

**Comment by bdunne** [comment]
@Fryguy I think this is fixed, right?

**Comment by Fryguy** [comment]
Yeah, I think so
