### ISSUE TITLE
Trello Bot

### ISSUE THREAD

**Issue by blomquisg** [ManageIQ/miq_bot#95]
### Goals of Using Trelllo
1. No one should have to touch the main roadmap board
   
   Team boards will drive the roadmap board.  And the roadmap board will largely be read-only.
2. Trello team boards should serve as the single place where devs can find things to work on.
   
   Bugzilla and Github will still be systems of record for bugs and pull requests, respectively.  But, Trello should be able to show the upcoming features as well as the bugs that are expected to be worked on for each sprint.
3. Product Managers should be able to see high level progress from roadmap.
   
   Trello team boards should feed the roadmap.  Items from various team board should be grouped together on the roadmap board by using consistent "tags" or labels across team boards.
4. Product Managers should be able to see specific team progress on team boards.
   
   Each team board should show the current status of work items for a sprint.
5. Team boards will have the same card lists:
   - **New**: The list of requirements from Product Management (or other sources) that have not yet been defined enough to scope
   - **Backlog**: The list of cards that have enough information to be scoped and have a decent time estimate.  This list is in rough priority order (most important on the top).
   - **Next**: The list of cards that could approximately build out the next one or two sprints.  This list is in rough priority order.
   - **In Progress**: The list of cards currently being worked on this sprint.
   - **Complete**: The list of cards completed during this sprint.  Cards can enter this list anytime during the sprint.
   - **Sprint &lt;NUMBER&gt;**: The list of cards that were completed for a given sprint.  Sprint cards can be archived and resurrected as need be.  We would likely keep four or five historical sprints in each team board at any time.  
### Trello Bot

Trello bot will help ensure that the team boards are in the correct state and display the correct information for each sprint.  However, it's still the responsibility of each team to make sure that the cards in Trello are kept up to date.
#### Requirements

**R1. Sync bugs from Bugzilla into Trello team boards**

  Each team board will have the same Bug cards for syncing bugs:
- **New Bugs**: A static card in the **New** list that contains the bugs assigned to the team but not yet assigned to any specific developer on the team.
- **Assigned Bugs**: A static card in the **Backlog** list that contains the bugs assigned to a specific developer on the team.
- **In Progress Bugs**: A static card in the **In Progress** list that contains the bugs in ON_DEV status and expected to be completed in that sprint.
- **Complete Bugs**: Static cards in the **Complete** and **Sprint &lt;NUMBER&gt;** lists that contain the lists of bugs in POST (and beyond) status.
  
  R1-1. Trello bot will maintain a mapping of Bugzilla Component to Trello team board.  Many Components may map to a single team board.
  
  R1-2. Bugs will be represented as Checklist Items in Bug cards in Trello.
  
  R1-3. Trello bot will watch for new bugs in Bugzilla for mapped components and create checklist items on the **New Bugs** card for the corresponding team.
  
  R1-4. Trello bot will watch for bugs that change from New to Assigned status in mapped components and move checklist items from the **New Bugs** card to the **Assigned Bugs** card for corresponding teams.
  
  R1-5. Trello bot will watch for bugs that change from Assigned to ON_DEV status in mapped components and move checklist items from the **Assigned Bugs** card to the **In Progress** card for corresponding teams.
  
  R1-6. Trello bot will watch for bugs that change from ON_DEV to POST status in mapped components and move checklist items from the **In Progress** card to the **Complete** card for corresponding teams.

**R2. Sync team boards to roadmap board

  Trello bot will make sure that the roadmap board reflects the collective work across all of the team boards.  The teams will make use of ad hoc "tagging" to group cards together into bigger epics that can be rolled together on the roadmap board.

-- More to come --

**Comment by chriskacerguis** [comment]
@miq-bot set_milestone Bot v2

**Comment by chriskacerguis** [comment]
@blomquisg is this still a thing since we are moving away from Trello?

**Comment by Fryguy** [comment]
Closing since we are no longer using Trello and the corresponding PR was closed as well.
